### ISSUE TITLE
Concord4pi creating Null Stub in MQTT Explorer

### ISSUE THREAD

**Issue by mkizito76** [ubiav/concord4pi#5]
After running for awhile (about 4 plus hours or so) I see a null stub created in MQTT Explorer (concord4pinull)
See attachment

![image](https://user-images.githubusercontent.com/1021010/75834967-3d5faa00-5d83-11ea-8890-95311bce5dc8.png)

**Comment by ubiav** [comment]
Can you share some of the messages in the concord4pinull topic?  Also the topic structure would be great.

**Comment by ubiav** [comment]
Found it.  This has been corrected.  In the AlarmTrouble class, the myAddress function was returnning null instead of the proper "address" of the object.  I updated the object and you should be getting this errant topic anymore.  Please test and I'll close, if fixed.

EDIT: I updated the JAR with this fix.

**Comment by mkizito76** [comment]
Here you go. And you are right, I imagined it was part of the "AlarmTrouble" class but  I was not sure. Below is the detail...
![image](https://user-images.githubusercontent.com/1021010/75877706-e4712f80-5ddd-11ea-85a9-d6c31dfdce08.png)

I will test it later today after I get the latest Jars.

**Comment by mkizito76** [comment]
I just started testing the code. All the testing I have done have worked as expected. I'll let is run overnight and see if the stub is created. I'll let you know ASAP.

Update:
I can confirm that the null stub is no longer being created and we can close this issue

**Comment by ubiav** [comment]
Issue fixed and closed.
